version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - postgres
      - redis
      - ai-governance
      - ai-cybersecurity

  ai-governance:
    build: ./ai-governance
    ports:
      - "8001:8000"

  ai-cybersecurity:
    build: ./ai-cybersecurity
    ports:
      - "8002:8000"

  postgres:
    image: postgres:15
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: